<x-mail::message>
# Teacher access request

{{ $user->name }} ({{ $user->email }}) requested permission to create classrooms.

<x-mail::button :url="$approvalUrl">
Review request
</x-mail::button>

This approval link was generated by {{ config('app.name') }}.
</x-mail::message>
